version: 2.1

parameters:
  environment:
    type: string
    default: "staging"
    enum: ["staging", "production"]

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            npm install

  deploy:
    docker:
      - image: circleci/node:14
    parameters:
      environment:
        type: string
    steps:
      - when:
          condition:
            or:
              - equal: [ << pipeline.parameters.environment >>, "staging" ]
              - equal: [ << pipeline.parameters.environment >>, "production" ]
          steps:
            - run:
                name: Deploy
                command: |
                  echo "Deploying to << parameters.environment >> environment."

